GetJob/Controllers/Teachers1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CleanArchitecture.DomainCore.Models;
using CleanArchitecture.Infrastucture.Data.Context;
using Google.Apis.Admin.Directory.directory_v1.Data;
using Microsoft.AspNetCore.Authorization;
using System.IO;

namespace GetJob.Controllers
{
    public class Teachers1Controller : Controller
    {
        private readonly GetJobDbContext _context;

        public Teachers1Controller(GetJobDbContext context)
        {
            _context = context;
        }
        
        // GET: Teachers1
        
        public async Task<IActionResult> Index(string text)
        {
            var result = new List<Teachers>();

            result = _context.Teachers.Where(x => x.Surname.Contains(text)).ToList();
            return View(result);
            
        }

        // GET: Teachers1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teachers = await _context.Teachers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teachers == null)
            {
                return NotFound();
            }

            return View(teachers);
        }

        // GET: Teachers1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Subjects_Taught,Level,Teacher_Image")] Teachers teachers)
        {
            if (ModelState.IsValid)
            {
                teachers.Teacher_Image = Path.GetFileName(teachers.Teacher_Image);
                _context.Add(teachers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teachers);
        }

        // GET: Teachers1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teachers = await _context.Teachers.FindAsync(id);
            if (teachers == null)
            {
                return NotFound();
            }
            return View(teachers);
        }

        // POST: Teachers1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Surname,Subjects_Taught,Level,Teacher_Image")] Teachers teachers)
        {
            if (id != teachers.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teachers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeachersExists(teachers.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teachers);
        }

        // GET: Teachers1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teachers = await _context.Teachers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teachers == null)
            {
                return NotFound();
            }

            return View(teachers);
        }

        // POST: Teachers1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teachers = await _context.Teachers.FindAsync(id);
            _context.Teachers.Remove(teachers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeachersExists(int id)
        {
            return _context.Teachers.Any(e => e.Id == id);
        }
    }
}

GetJob/Views/Teachers1/Create.cshtml
@model CleanArchitecture.DomainCore.Models.Teachers

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Teachers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subjects_Taught" class="control-label"></label>
                <input asp-for="Subjects_Taught" class="form-control" />
                <span asp-validation-for="Subjects_Taught" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Level" class="control-label"></label>
                <input asp-for="Level" class="form-control" />
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Teacher_Image" class="control-label"></label>
                <input asp-for="Teacher_Image" class="form-control" />
                <span asp-validation-for="Teacher_Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

GetJob/Views/Teachers1/Delete.cshtml
@model CleanArchitecture.DomainCore.Models.Teachers

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teachers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subjects_Taught)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subjects_Taught)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Level)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Level)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher_Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher_Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GetJob/Views/Teachers1/Details.cshtml
@model CleanArchitecture.DomainCore.Models.Teachers

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Teachers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subjects_Taught)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subjects_Taught)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Level)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Level)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher_Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher_Image)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GetJob/Views/Teachers1/Edit.cshtml
@model CleanArchitecture.DomainCore.Models.Teachers

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Teachers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subjects_Taught" class="control-label"></label>
                <input asp-for="Subjects_Taught" class="form-control" />
                <span asp-validation-for="Subjects_Taught" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Level" class="control-label"></label>
                <input asp-for="Level" class="form-control" />
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Teacher_Image" class="control-label"></label>
                <input asp-for="Teacher_Image" class="form-control" />
                <span asp-validation-for="Teacher_Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

GetJob/Views/Teachers1/Index.cshtml
@model IEnumerable<CleanArchitecture.DomainCore.Models.Teachers>

@{
    ViewData["Title"] = "Index";
}

<h4>Преподаватели</h4>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Teachers1" asp-action="Index">
    <p>
        Фамилия: <input type="text" name="text" />
        <input type="submit" value="Поиск" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Имя 
            </th>
            <th>
               Фамилия
            </th>
            <th>
                Дисциплина 
            </th>
            <th>
               Уровень
            </th>
            <th>
               Фото
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subjects_Taught)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Level)
            </td>
            <td>
                @if (item.Teacher_Image != null)
                {
                    <img style='width:80px; height:60px;' src="@Url.Content(item.Teacher_Image)" )" />
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>