GetJob/Controllers/Students1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CleanArchitecture.DomainCore.Models;
using CleanArchitecture.Infrastucture.Data.Context;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace GetJob.Controllers
{
    public class Students1Controller : Controller
    {
        private readonly GetJobDbContext _context;

        public Students1Controller(GetJobDbContext context)
        {
            _context = context;
        }

        // GET: Students1
        [Authorize(Roles = "admin")]
      
        public async Task<IActionResult> Index(string text)
        {
            
            var result = new List<Students>();
            /*for(int i = 0; i < result.Count; i++)
            {
                result[i].Student_Image =  System.IO.Path.GetFullPath(_context.Students.Find(result[i].Student_Image));
            }
            */
            result = _context.Students.Where(x => x.Name.Contains(text)).ToList();
           return View(result);
            
        }

        // GET: Students1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (students == null)
            {
                return NotFound();
            }

            return View(students);
        }

        // GET: Students1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Name_of_Course,Number_of_Course,Nation,Date_of_Birth,Student_Image")] Students students)
        {
            if (ModelState.IsValid)
            {
                students.Student_Image= Path.GetFileName(students.Student_Image);

                _context.Add(students);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(students);
        }

        // GET: Students1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _context.Students.FindAsync(id);
            if (students == null)
            {
                return NotFound();
            }
            return View(students);
        }

        // POST: Students1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Surname,Name_of_Course,Number_of_Course,Nation,Date_of_Birth,Student_Image")] Students students)
        {
            if (id != students.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(students);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentsExists(students.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(students);
        }

        // GET: Students1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var students = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (students == null)
            {
                return NotFound();
            }

            return View(students);
        }

        // POST: Students1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var students = await _context.Students.FindAsync(id);
            _context.Students.Remove(students);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentsExists(int id)
        {
            return _context.Students.Any(e => e.Id == id);
        }
    }
}

GetJob/Views/Students1/Create.cshtml
@model CleanArchitecture.DomainCore.Models.Students

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Students</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name_of_Course" class="control-label"></label>
                <input asp-for="Name_of_Course" class="form-control" />
                <span asp-validation-for="Name_of_Course" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number_of_Course" class="control-label"></label>
                <input asp-for="Number_of_Course" class="form-control" />
                <span asp-validation-for="Number_of_Course" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date_of_Birth" class="control-label"></label>
                <input asp-for="Date_of_Birth" class="form-control" />
                <span asp-validation-for="Date_of_Birth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student_Image" class="control-label"></label>
                <input asp-for="Student_Image" class="form-control" />

                <span asp-validation-for="Student_Image" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Nation" class="control-label"></label>
                <input asp-for="Nation" class="form-control" />

                <span asp-validation-for="Nation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

GetJob/Views/Students1/Delete.cshtml
@model CleanArchitecture.DomainCore.Models.Students

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Students</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name_of_Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name_of_Course)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Number_of_Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Number_of_Course)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date_of_Birth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date_of_Birth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student_Image)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student_Image)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nation)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GetJob/Views/Students1/Details.cshtml
@model CleanArchitecture.DomainCore.Models.Students

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Students</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name_of_Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name_of_Course)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Number_of_Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Number_of_Course)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date_of_Birth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date_of_Birth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student_Image)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student_Image)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nation)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GetJob/Views/Students1/Edit.cshtml
@model CleanArchitecture.DomainCore.Models.Students

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Students</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name_of_Course" class="control-label"></label>
                <input asp-for="Name_of_Course" class="form-control" />
                <span asp-validation-for="Name_of_Course" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number_of_Course" class="control-label"></label>
                <input asp-for="Number_of_Course" class="form-control" />
                <span asp-validation-for="Number_of_Course" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date_of_Birth" class="control-label"></label>
                <input asp-for="Date_of_Birth" class="form-control" />
                <span asp-validation-for="Date_of_Birth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Student_Image" class="control-label"></label>
                <input asp-for="Student_Image" class="form-control" />
                <span asp-validation-for="Student_Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nation" class="control-label"></label>
                <input asp-for="Nation" class="form-control" />
                <span asp-validation-for="Nation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

GetJob/Views/Students1/Index.cshtml
@model IEnumerable<CleanArchitecture.DomainCore.Models.Students>

@{
    ViewData["Title"] = "Index";
}



<p>Вход только админам </p>
<h4>Студенты</h4>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Students1" asp-action="Index">
    <p>
        Title: <input type="text" name="text" />
        <input type="submit" value="Поиск" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Имя
            </th>
            <th>
                Фамилия
            </th>
            <th>
                Специальность
            </th>
            <th>
                Курс
            </th>
            <th>
                Дата рождения
            </th>
            <th>
                Фото
            </th>
            <th>
                Нация
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name_of_Course)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number_of_Course)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date_of_Birth)

            </td>

            <td>

                @if (item.Student_Image != null)
                {
                    <img style='width:80px; height:60px;' src="@Url.Content(item.Student_Image)" )" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nation)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>